Update buid.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -27,31 +27,46 @@ jobs:
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
+
       - name: Clone repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
-          submodules: recursive
+          submodules: true
 
       - name: Setup HarmonyOS CLI tools
         uses: ErBWs/setup-ohos@v1
         with:
           version: latest
           cache: true
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl libgl1-mesa-dev
+        shell: bash
+      - run: hvigorw -v
 
       - name: Install project dependencies
         run: |
-          ohpm install --all
+          ohpm install --all --rt 5 --ri 5000
 
       - name: Build hap
         run: hvigorw clean assembleHap -p buildMode=release --config properties.ignoreSignHap=true
         shell: bash
 
       - name: Rename hap
-        run: cp /home/runner/work/ohtotptoken/ohtotptoken/entry/build/default/outputs/default/entry-default-unsigned.hap ohtotptoken_ohos_canary.hap
+        run: |
+          HAP_FILE=$(find "${{ github.workspace }}/entry/build" -name "*.hap" -type f | head -n 1)
+          if [ -z "$HAP_FILE" ]; then
+            echo "::error::No hap file found in build output!"
+            exit 1
+          fi
+          echo "Found hap: $HAP_FILE"
+          cp "$HAP_FILE" "${{ github.workspace }}/ohtotptoken_ohos_canary.hap"
 
       - name: Upload hap
         uses: actions/upload-artifact@v4
         with:
           name: ohos_outputs
-          path: ohtotptoken_ohos_canary.hap
-          retention-days: 3
+          path: ${{ github.workspace }}/ohtotptoken_ohos_canary.hap
+          if-no-files-found: error
+          retention-days: 30
